# -*- coding: utf-8 -*-
"""file_operations.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAE5_LhfQ98mdtLOOHkwlf6t_yElektg
"""

# Task 2: Write and Append Data to a File

def main():
    filename = 'output.txt'

    # 1. Take user input and write to the file
    # 'w' mode writes to the file (and overwrites it if it exists)
    user_text = input("Enter text to write to the file: ")

    with open(filename, 'w') as file:
        file.write(user_text + "\n") # Add a newline character

    print(f"Data successfully written to {filename}.\n")

    # 2. Append additional data
    # 'a' mode appends to the end of the file without deleting existing content
    append_text = input("Enter additional text to append: ")

    with open(filename, 'a') as file:
        file.write(append_text + "\n")

    print("Data successfully appended.\n")

    # 3. Read and display the final content
    print(f"Final content of {filename}:")

    with open(filename, 'r') as file:
        content = file.read()
        print(content)

if __name__ == "__main__":
    main()