# -*- coding: utf-8 -*-
"""read_file.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAE5_LhfQ98mdtLOOHkwlf6t_yElektg
"""

# Task 1: Read a File and Handle Errors

def main():
    filename = 'sample.txt'

    try:
        # 1. Open and read the file
        # 'r' mode opens the file for reading
        with open(filename, 'r') as file:
            print("Reading file content:")

            # 2. Print content line by line
            # enumerate helps us count the line numbers (starting from 1)
            for i, line in enumerate(file, start=1):
                # .strip() removes the extra newline character at the end of each line
                print(f"Line {i}: {line.strip()}")

    except FileNotFoundError:
        # 3. Handle errors gracefully if the file does not exist
        print(f"Error: The file '{filename}' was not found.")

if __name__ == "__main__":
    main()